version: '3.4'

services:
  apitesting:
    image: cordfinancetest
    container_name: cordfinancetest
    build: 
        context: src/
        dockerfile: debug.Dockerfile
    command:
      run https://www.getpostman.com/collections/bd9af4efe8967ccdc9ff
      -e environments/env.json
      -d environments/data2V.json
      -r htmlextra,cli 
      --reporter-htmlextra-export reports/CFAPITestReport.html
    volumes:
        - ./src:/etc/newman
    networks:
      - cordfinance
    expose:
      - "80"
  
networks:
  cordfinance:
    driver: bridge
